#!/usr/bin/env bash
# ==============================================================================
# Neon PostgreSQL -> Google Drive Automated Backup Script
# Project: my-neon-project
# Generated by: Neon2Drive Backup Automator
# Schedule: 0 2 * * * (UTC)
# ==============================================================================

set -euo pipefail

# 1. Load environment variables if .env exists
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ -f "$SCRIPT_DIR/.env" ]; then
  # export variables safely
  set -a
  # shellcheck source=/dev/null
  source "$SCRIPT_DIR/.env"
  set +a
fi

# 2. Configuration & Defaults
DATABASE_URL="${DATABASE_URL:-"postgresql://neondb_owner:npg_secret123@ep-cool-fog-123456.us-east-2.aws.neon.tech/neondb?sslmode=require"}"
GDRIVE_FOLDER_ID="${GDRIVE_FOLDER_ID:-"1AbCdEfGhIjKlMnOpQrStUvWxYz12345"}"
LOCAL_BACKUP_DIR="${LOCAL_BACKUP_DIR:-"./backups"}"
RETENTION_DAYS_LOCAL="${RETENTION_DAYS_LOCAL:-7}"
WEBHOOK_URL="${WEBHOOK_URL:-"https://discord.com/api/webhooks/123456789/abcdefghijk"}"
HEALTHCHECK_URL="${HEALTHCHECK_URL:-"https://hc-ping.com/your-uuid-here"}"
SERVICE_ACCOUNT_KEY="${SERVICE_ACCOUNT_KEY_FILE:-"./service-account-key.json"}"

TIMESTAMP="$(date +"%Y-%m-%d_%H%M%S")"
PROJECT_SLUG="my-neon-project"
BACKUP_FILENAME="${PROJECT_SLUG}_${TIMESTAMP}.dump"
LOCAL_FILEPATH="${LOCAL_BACKUP_DIR}/${BACKUP_FILENAME}"
LOG_FILE="${LOCAL_BACKUP_DIR}/backup.log"

# Ensure local backup directory exists
mkdir -p "$LOCAL_BACKUP_DIR"

log() {
  local msg="[$(date +"%Y-%m-%d %H:%M:%S %Z")] $1"
  echo "$msg" | tee -a "$LOG_FILE"
}

send_webhook() {
  local status="$1"
  local details="$2"
  if [ -n "$WEBHOOK_URL" ]; then
    local payload
    payload=$(cat <<EOF
{
  "content": "${status}: Neon DB Backup for 'my-neon-project'\n> **File**: \`${BACKUP_FILENAME}\`\n> **Details**: ${details}\n> **Time**: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
}
EOF
    )
    curl -s -X POST -H "Content-Type: application/json" -d "$payload" "$WEBHOOK_URL" >/dev/null 2>&1 || true
  fi
}

send_healthcheck() {
  local status="$1"
  if [ -n "$HEALTHCHECK_URL" ]; then
    if [ "$status" = "success" ]; then
      curl -fsS -m 10 --retry 3 "$HEALTHCHECK_URL" >/dev/null 2>&1 || true
    else
      curl -fsS -m 10 --retry 3 "${HEALTHCHECK_URL}/fail" >/dev/null 2>&1 || true
    fi
  fi
}

log "================================================================="
log "Starting Neon PostgreSQL Backup for project 'my-neon-project'"

# 3. Check for pg_dump or docker
USE_DOCKER=false
if command -v docker &> /dev/null; then
  USE_DOCKER=true
  log "Docker detected. Using 'postgres:latest' docker container for pg_dump (prevents version mismatch)."
elif command -v pg_dump &> /dev/null; then
  log "Using system 'pg_dump' utility..."
else
  log "ERROR: Neither 'docker' nor 'pg_dump' command was found! Please install postgresql-client or docker."
  send_webhook "🚨 FAILED" "'pg_dump' and 'docker' utilities not found on host."
  send_healthcheck "fail"
  exit 1
fi

# 4. Perform PostgreSQL Dump
log "Dumping database from Neon..."
START_TIME=$(date +%s)

ABS_BACKUP_DIR="$(cd "$LOCAL_BACKUP_DIR" && pwd)"

if [ "$USE_DOCKER" = true ]; then
  docker run --rm -v "${ABS_BACKUP_DIR}:/backups" postgres:latest pg_dump "$DATABASE_URL" -Fc --no-owner --no-acl -f "/backups/${BACKUP_FILENAME}"
else
  pg_dump "$DATABASE_URL" -Fc --no-owner --no-acl -f "$LOCAL_FILEPATH"
fi

END_TIME=$(date +%s)
DURATION=$((END_TIME - START_TIME))

if [ ! -s "$LOCAL_FILEPATH" ]; then
  log "ERROR: Backup file was created but is empty or missing: $LOCAL_FILEPATH"
  send_webhook "🚨 FAILED" "Dump created an empty file (0 bytes)."
  send_healthcheck "fail"
  exit 1
fi

FILE_SIZE=$(du -h "$LOCAL_FILEPATH" | cut -f1)
log "✓ Database dump successful: $BACKUP_FILENAME (Size: $FILE_SIZE, Took: ${DURATION}s)"



# 5. Upload to Google Drive
log "Uploading $BACKUP_FILENAME to Google Drive (Folder ID: $GDRIVE_FOLDER_ID)..."

UPLOAD_SUCCESS=false

# Method A: Try Node.js uploader (built-in, uses Google Service Account)
if [ -f "$SCRIPT_DIR/uploader.js" ] && command -v node &> /dev/null; then
  log "Using Node.js Google Drive API uploader..."
  if node "$SCRIPT_DIR/uploader.js" "$LOCAL_FILEPATH" "$GDRIVE_FOLDER_ID" "$SERVICE_ACCOUNT_KEY"; then
    UPLOAD_SUCCESS=true
  fi
# Method B: Try rclone if configured
elif command -v rclone &> /dev/null; then
  log "Using Rclone to upload to Google Drive..."
  if rclone copy "$LOCAL_FILEPATH" "gdrive:${GDRIVE_FOLDER_ID}"; then
    UPLOAD_SUCCESS=true
  fi
# Method C: Try gdrive CLI if installed
elif command -v gdrive &> /dev/null; then
  log "Using gdrive CLI..."
  if gdrive files upload --parent "$GDRIVE_FOLDER_ID" "$LOCAL_FILEPATH"; then
    UPLOAD_SUCCESS=true
  fi
else
  log "WARNING: No Google Drive upload utility found (neither node uploader.js, rclone, nor gdrive)."
  log "The file is safely saved locally at: $LOCAL_FILEPATH"
fi

if [ "$UPLOAD_SUCCESS" = true ]; then
  log "✓ Successfully uploaded to Google Drive!"
  
  send_healthcheck "success"
else
  log "⚠️ Google Drive upload failed or skipped. Backup preserved locally."
  send_webhook "⚠️ WARNING" "Backup saved locally ($FILE_SIZE), but Google Drive upload was not completed."
fi

# 6. Local Retention Policy: Clean up old local backups
log "Applying retention policy: Deleting local backups older than $RETENTION_DAYS_LOCAL days..."
find "$LOCAL_BACKUP_DIR" -type f \( -name "*.dump" -o -name "*.sql" -o -name "*.sql.gz" -o -name "*.enc" \) -mtime +"$RETENTION_DAYS_LOCAL" -exec rm -f {} \;
log "✓ Retention cleanup complete."

log "Neon Backup Process Finished Successfully."
log "================================================================="
